import Foundation

// MARK: - State Voting Data for all 50 states + DC

struct VotingDataStore {
    static let states: [StateVotingInfo] = [
        StateVotingInfo(id: "AL", name: "Alabama", registrationDeadlineDays: 15, onlineRegistration: true, sameDayRegistration: false, earlyVoting: false, earlyVotingDays: nil, noExcuseAbsentee: false, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State-issued photo ID", "Passport", "Military ID", "Tribal ID"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://www.sos.alabama.gov/alabama-votes", keyInfo: ["One of few states with no early voting", "Photo ID strictly required"]),

        StateVotingInfo(id: "AK", name: "Alaska", registrationDeadlineDays: 30, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 15, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "State ID", "Voter registration card", "Hunting/fishing license", "Utility bill"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://www.elections.alaska.gov", keyInfo: ["Uses ranked-choice voting", "Same-day registration available", "No-excuse absentee voting"]),

        StateVotingInfo(id: "AZ", name: "Arizona", registrationDeadlineDays: 29, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 27, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "Tribal ID", "Two non-photo IDs (utility bill, bank statement)"], pollingHours: "6:00 AM - 7:00 PM", stateWebsite: "https://azsos.gov/elections", keyInfo: ["Early voting starts 27 days before election", "Permanent early voting list available"]),

        StateVotingInfo(id: "AR", name: "Arkansas", registrationDeadlineDays: 30, onlineRegistration: false, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 15, noExcuseAbsentee: false, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State photo ID", "Passport", "Military ID"], pollingHours: "7:30 AM - 7:30 PM", stateWebsite: "https://www.sos.arkansas.gov/elections", keyInfo: ["No online voter registration", "Photo ID required", "Early voting available"]),

        StateVotingInfo(id: "CA", name: "California", registrationDeadlineDays: 15, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 29, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID required at polls — first-time voters may need to show ID"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://www.sos.ca.gov/elections", keyInfo: ["All voters receive mail ballots automatically", "Same-day registration available", "No ID required at polls"]),

        StateVotingInfo(id: "CO", name: "Colorado", registrationDeadlineDays: 8, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 22, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "Passport", "Medicare card", "Utility bill", "Bank statement"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://www.coloradosos.gov/pubs/elections", keyInfo: ["All-mail ballot state", "Same-day registration", "Voter service and polling centers available"]),

        StateVotingInfo(id: "CT", name: "Connecticut", registrationDeadlineDays: 7, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 14, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "State ID", "Social Security card", "Utility bill", "Credit card with name"], pollingHours: "6:00 AM - 8:00 PM", stateWebsite: "https://portal.ct.gov/sots/election-services", keyInfo: ["Early voting recently enacted", "Same-day registration available"]),

        StateVotingInfo(id: "DE", name: "Delaware", registrationDeadlineDays: 24, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 10, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "State ID", "Utility bill", "Paycheck", "Government document"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://elections.delaware.gov", keyInfo: ["Early voting available", "No-excuse absentee voting"]),

        StateVotingInfo(id: "FL", name: "Florida", registrationDeadlineDays: 29, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 15, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Student ID", "Retirement center ID"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://dos.fl.gov/elections", keyInfo: ["Early voting period: 15-1 days before election", "Photo ID required but not strict"]),

        StateVotingInfo(id: "GA", name: "Georgia", registrationDeadlineDays: 29, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 21, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State photo ID", "Passport", "Military ID", "Employee photo ID"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://sos.ga.gov/elections", keyInfo: ["Three weeks of early voting", "Strict photo ID for in-person and absentee"]),

        StateVotingInfo(id: "HI", name: "Hawaii", registrationDeadlineDays: 29, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 18, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "State ID", "Utility bill", "Bank statement", "Paycheck"], pollingHours: "7:00 AM - 6:00 PM", stateWebsite: "https://elections.hawaii.gov", keyInfo: ["All-mail election state", "Same-day registration", "Voter service centers available on Election Day"]),

        StateVotingInfo(id: "ID", name: "Idaho", registrationDeadlineDays: 25, onlineRegistration: false, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 19, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Concealed weapons license", "Tribal photo ID"], pollingHours: "8:00 AM - 8:00 PM", stateWebsite: "https://sos.idaho.gov/elections", keyInfo: ["Same-day registration at the polls", "No online voter registration"]),

        StateVotingInfo(id: "IL", name: "Illinois", registrationDeadlineDays: 28, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 40, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID required — first-time voters who registered by mail may need ID"], pollingHours: "6:00 AM - 7:00 PM", stateWebsite: "https://www.elections.il.gov", keyInfo: ["Early voting starts 40 days before election", "Same-day registration available", "No ID required for most voters"]),

        StateVotingInfo(id: "IN", name: "Indiana", registrationDeadlineDays: 29, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 28, noExcuseAbsentee: false, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State photo ID", "Military ID", "Passport"], pollingHours: "6:00 AM - 6:00 PM", stateWebsite: "https://www.in.gov/sos/elections", keyInfo: ["Strict photo ID required", "Absentee voting requires an excuse"]),

        StateVotingInfo(id: "IA", name: "Iowa", registrationDeadlineDays: 15, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 20, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Tribal photo ID"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://sos.iowa.gov/elections", keyInfo: ["Same-day registration available", "Photo ID strictly required since 2024"]),

        StateVotingInfo(id: "KS", name: "Kansas", registrationDeadlineDays: 21, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 20, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Concealed carry license"], pollingHours: "7:00 AM - 7:00 PM (varies by county)", stateWebsite: "https://www.sos.ks.gov/elections", keyInfo: ["Advance voting available", "Photo ID required since 2012"]),

        StateVotingInfo(id: "KY", name: "Kentucky", registrationDeadlineDays: 29, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 3, noExcuseAbsentee: false, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Credit card with photo"], pollingHours: "6:00 AM - 6:00 PM", stateWebsite: "https://elect.ky.gov", keyInfo: ["Limited early voting (3 days before)", "Absentee requires excuse"]),

        StateVotingInfo(id: "LA", name: "Louisiana", registrationDeadlineDays: 30, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 14, noExcuseAbsentee: false, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "LA wallet digital ID"], pollingHours: "6:00 AM - 8:00 PM", stateWebsite: "https://www.sos.la.gov/ElectionsAndVoting", keyInfo: ["Digital ID (LA Wallet) accepted", "Absentee requires excuse"]),

        StateVotingInfo(id: "ME", name: "Maine", registrationDeadlineDays: 21, onlineRegistration: false, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 30, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID required at polls"], pollingHours: "6:00 AM - 8:00 PM (varies by town)", stateWebsite: "https://www.maine.gov/sos/cec/elec", keyInfo: ["Uses ranked-choice voting for federal races", "Same-day registration", "No ID required"]),

        StateVotingInfo(id: "MD", name: "Maryland", registrationDeadlineDays: 21, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 8, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID required for registered voters — first-time voters may need ID"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://elections.maryland.gov", keyInfo: ["Same-day registration during early voting", "No-excuse mail-in voting"]),

        StateVotingInfo(id: "MA", name: "Massachusetts", registrationDeadlineDays: 10, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 17, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID generally required — first-time voters who registered by mail may need ID"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://www.sec.state.ma.us/divisions/elections", keyInfo: ["Early voting and no-excuse mail voting", "Same-day registration available"]),

        StateVotingInfo(id: "MI", name: "Michigan", registrationDeadlineDays: 15, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 9, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Tribal ID", "Student ID with photo"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://mvic.sos.state.mi.us", keyInfo: ["Same-day registration available", "No-excuse absentee voting since 2018"]),

        StateVotingInfo(id: "MN", name: "Minnesota", registrationDeadlineDays: 21, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 46, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No photo ID required — can use registered voter vouching, utility bill, or government document"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://www.sos.state.mn.us/elections-voting", keyInfo: ["One of the earliest early voting periods (46 days)", "Same-day registration at the polls"]),

        StateVotingInfo(id: "MS", name: "Mississippi", registrationDeadlineDays: 30, onlineRegistration: false, sameDayRegistration: false, earlyVoting: false, earlyVotingDays: nil, noExcuseAbsentee: false, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Tribal ID", "Firearms license"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://www.sos.ms.gov/elections-voting", keyInfo: ["No online registration", "No early voting", "No no-excuse absentee", "Strict photo ID"]),

        StateVotingInfo(id: "MO", name: "Missouri", registrationDeadlineDays: 27, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 14, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID"], pollingHours: "6:00 AM - 7:00 PM", stateWebsite: "https://www.sos.mo.gov/elections", keyInfo: ["Photo ID required", "No-excuse absentee voting available"]),

        StateVotingInfo(id: "MT", name: "Montana", registrationDeadlineDays: 30, onlineRegistration: false, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 30, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "State ID", "Military ID", "Tribal ID", "Utility bill", "Bank statement"], pollingHours: "7:00 AM - 8:00 PM (varies by county)", stateWebsite: "https://sosmt.gov/elections", keyInfo: ["Late registration available at county offices", "All-mail elections in some counties"]),

        StateVotingInfo(id: "NE", name: "Nebraska", registrationDeadlineDays: 18, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 30, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID"], pollingHours: "7:00 AM - 7:00 PM (8 AM - 8 PM in some areas)", stateWebsite: "https://sos.nebraska.gov/elections", keyInfo: ["Splits Electoral College votes by congressional district", "Photo ID required starting 2024"]),

        StateVotingInfo(id: "NV", name: "Nevada", registrationDeadlineDays: 28, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 14, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID required at polls for registered voters"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://www.nvsos.gov/sos/elections", keyInfo: ["All voters receive mail ballots automatically", "Same-day registration", "14 days early voting"]),

        StateVotingInfo(id: "NH", name: "New Hampshire", registrationDeadlineDays: 6, onlineRegistration: false, sameDayRegistration: true, earlyVoting: false, earlyVotingDays: nil, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Voter ID card (free)"], pollingHours: "Varies by town (some open as early as 6:00 AM)", stateWebsite: "https://www.sos.nh.gov/elections", keyInfo: ["Same-day registration on Election Day", "No early voting", "Free voter ID card available"]),

        StateVotingInfo(id: "NJ", name: "New Jersey", registrationDeadlineDays: 21, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 10, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID required for registered voters — first-time voters may need ID"], pollingHours: "6:00 AM - 8:00 PM", stateWebsite: "https://www.nj.gov/state/elections", keyInfo: ["Early voting recently established", "No-excuse vote-by-mail"]),

        StateVotingInfo(id: "NM", name: "New Mexico", registrationDeadlineDays: 28, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 28, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "State ID", "Utility bill", "Bank statement", "Government check", "Paycheck"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://www.sos.nm.gov/voting-and-elections", keyInfo: ["28 days of early voting", "Same-day registration"]),

        StateVotingInfo(id: "NY", name: "New York", registrationDeadlineDays: 25, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 10, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID required for registered voters"], pollingHours: "6:00 AM - 9:00 PM", stateWebsite: "https://www.elections.ny.gov", keyInfo: ["10 days of early voting", "No-excuse absentee voting", "Polls open until 9 PM"]),

        StateVotingInfo(id: "NC", name: "North Carolina", registrationDeadlineDays: 25, onlineRegistration: false, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 19, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military/veteran ID", "Tribal photo ID"], pollingHours: "6:30 AM - 7:30 PM", stateWebsite: "https://www.ncsbe.gov", keyInfo: ["Same-day registration during early voting only", "Photo ID required", "19 days of early voting"]),

        StateVotingInfo(id: "ND", name: "North Dakota", registrationDeadlineDays: nil, onlineRegistration: false, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 15, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "State ID", "Tribal ID", "Long-term care ID"], pollingHours: "Varies by county (generally 7:00 AM - 7:00 PM)", stateWebsite: "https://vip.sos.nd.gov", keyInfo: ["Only state with NO voter registration requirement", "Must show valid ID with current address"]),

        StateVotingInfo(id: "OH", name: "Ohio", registrationDeadlineDays: 30, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 29, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID"], pollingHours: "6:30 AM - 7:30 PM", stateWebsite: "https://www.ohiosos.gov/elections-voting", keyInfo: ["29 days of early in-person voting", "Strict photo ID required"]),

        StateVotingInfo(id: "OK", name: "Oklahoma", registrationDeadlineDays: 25, onlineRegistration: false, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 3, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Voter registration card"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://oklahoma.gov/elections", keyInfo: ["Short early voting period", "Voter registration card with photo accepted"]),

        StateVotingInfo(id: "OR", name: "Oregon", registrationDeadlineDays: 21, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 18, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID required — all-mail voting state"], pollingHours: "Ballots due by 8:00 PM on Election Day", stateWebsite: "https://sos.oregon.gov/voting-elections", keyInfo: ["All-mail voting state since 2000", "No polling places — drop off or mail ballots", "Automatic voter registration"]),

        StateVotingInfo(id: "PA", name: "Pennsylvania", registrationDeadlineDays: 15, onlineRegistration: true, sameDayRegistration: false, earlyVoting: false, earlyVotingDays: nil, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Utility bill", "Bank statement (first-time voters)"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://www.vote.pa.gov", keyInfo: ["No true early voting — mail-in ballots available", "No-excuse mail-in voting since 2020"]),

        StateVotingInfo(id: "RI", name: "Rhode Island", registrationDeadlineDays: 30, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 20, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Government photo ID"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://elections.ri.gov", keyInfo: ["20 days of early voting", "Photo ID required"]),

        StateVotingInfo(id: "SC", name: "South Carolina", registrationDeadlineDays: 30, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 15, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State photo ID", "Passport", "Military ID", "Voter registration card with photo"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://scvotes.gov", keyInfo: ["Free voter registration card with photo available", "Strict photo ID required"]),

        StateVotingInfo(id: "SD", name: "South Dakota", registrationDeadlineDays: 15, onlineRegistration: false, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 46, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Student ID", "Tribal ID"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://sdsos.gov/elections-voting", keyInfo: ["Very long early voting period (46 days)", "No online registration"]),

        StateVotingInfo(id: "TN", name: "Tennessee", registrationDeadlineDays: 30, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 20, noExcuseAbsentee: false, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State photo ID", "Passport", "Military ID"], pollingHours: "Varies by county (generally 8:00 AM - 7:00 PM/8:00 PM)", stateWebsite: "https://sos.tn.gov/elections", keyInfo: ["Strict photo ID required", "Absentee requires excuse", "20 days early voting"]),

        StateVotingInfo(id: "TX", name: "Texas", registrationDeadlineDays: 30, onlineRegistration: false, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 17, noExcuseAbsentee: false, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State photo ID", "Passport", "Military ID", "Concealed handgun license", "Election ID certificate (free)"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://www.sos.texas.gov/elections", keyInfo: ["No online voter registration", "Strict photo ID", "Absentee requires excuse (age 65+, disability, travel)"]),

        StateVotingInfo(id: "UT", name: "Utah", registrationDeadlineDays: 11, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 14, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Utility bill", "Bank statement"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://vote.utah.gov", keyInfo: ["All-mail voting state", "Same-day registration available", "Vote centers instead of precinct polling"]),

        StateVotingInfo(id: "VT", name: "Vermont", registrationDeadlineDays: 0, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 45, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID required at polls"], pollingHours: "5:00 AM - 7:00 PM (varies by town)", stateWebsite: "https://sos.vermont.gov/elections", keyInfo: ["All voters receive mail ballots", "Same-day registration", "No ID required", "Registration deadline is Election Day"]),

        StateVotingInfo(id: "VA", name: "Virginia", registrationDeadlineDays: 22, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 45, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Employer photo ID", "Student ID", "Voter photo ID (free)"], pollingHours: "6:00 AM - 7:00 PM", stateWebsite: "https://www.elections.virginia.gov", keyInfo: ["45 days of early voting", "Free voter photo ID available", "No-excuse absentee"]),

        StateVotingInfo(id: "WA", name: "Washington", registrationDeadlineDays: 8, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 18, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID required — all-mail voting state"], pollingHours: "Ballots due by 8:00 PM on Election Day", stateWebsite: "https://www.sos.wa.gov/elections", keyInfo: ["All-mail voting state", "Same-day registration", "Ballots mailed ~18 days before election"]),

        StateVotingInfo(id: "WV", name: "West Virginia", registrationDeadlineDays: 21, onlineRegistration: true, sameDayRegistration: false, earlyVoting: true, earlyVotingDays: 13, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Utility bill", "Bank statement", "Government check"], pollingHours: "6:30 AM - 7:30 PM", stateWebsite: "https://sos.wv.gov/elections", keyInfo: ["No-excuse early voting", "Non-photo ID accepted"]),

        StateVotingInfo(id: "WI", name: "Wisconsin", registrationDeadlineDays: 20, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 14, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Strict Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Tribal ID", "Student ID (with specific requirements)"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://elections.wi.gov", keyInfo: ["Same-day registration at the polls", "Strict photo ID required", "Student IDs must meet specific criteria"]),

        StateVotingInfo(id: "WY", name: "Wyoming", registrationDeadlineDays: 14, onlineRegistration: false, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 40, noExcuseAbsentee: true, voterIDRequired: true, voterIDType: "Non-Photo", acceptedIDs: ["Driver's license", "State ID", "Passport", "Military ID", "Utility bill", "Bank statement"], pollingHours: "7:00 AM - 7:00 PM", stateWebsite: "https://sos.wyo.gov/Elections", keyInfo: ["Same-day registration", "No online registration"]),

        StateVotingInfo(id: "DC", name: "District of Columbia", registrationDeadlineDays: 21, onlineRegistration: true, sameDayRegistration: true, earlyVoting: true, earlyVotingDays: 13, noExcuseAbsentee: true, voterIDRequired: false, voterIDType: "None", acceptedIDs: ["No ID required for registered voters"], pollingHours: "7:00 AM - 8:00 PM", stateWebsite: "https://www.dcboe.org", keyInfo: ["Same-day registration", "No ID required", "No-excuse mail voting"]),
    ]

    static func state(for id: String) -> StateVotingInfo? {
        states.first { $0.id == id }
    }

    static func state(named name: String) -> StateVotingInfo? {
        states.first { $0.name == name }
    }
}
